owner: aimxhaisse
repo: gitmon

sites:
  - name: SBRK
    url: https://sbrk.org
  - name: BLZ Audio
    url: https://blz.sbrk.org
  - name: MXS Blog
    url: https://mxs.sbrk.org/
  - name: MXS Landing
    url: https://landing.mxs.sbrk.org/
  - name: MXS Detours
    url: https://detours.sbrk.org
  - name: MXS Sandwalker
    url: https://sandwalker.sbrk.org/

assignees:
  - aimxhaisse

status-website:
  theme: dark
  baseUrl: /gitmon
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MXS' Monitoring
  introTitle: "White Box Monitoring for mxs"
  introMessage: Howdy Merry Folk.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"
